steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/go_sample"]
    env: ["PROJECT_ROOT=github.com/go_sample"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/build-images/go_sample:${REVISION_ID}", "-f", "Dockerfile", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/build-images/go_sample:${REVISION_ID}", "gcr.io/build-images/go_sample:latest"]
images:
  - "gcr.io/build-images/go_sample:${REVISION_ID}"
