steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/go_sample"]
    env: ["PROJECT_ROOT=github.com/go_sample"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/ci-sample-198806/go_sample:v1", "-f", "Dockerfile", "."]
images:
  - "gcr.io/ci-sample-198806/go_sample:v1"
