defaults: &defaults
  environment:
    PROJECT_ID: build-images
    STAGING_CLUSTER_PROJECT_ID: ci-staging-198906
    PRODUCTION_CLUSTER_PROJECT_ID: ci-sample-198806
    CLUSTER_NAME: cluster-app
    COMPUTE_ZONE: asia-northeast1-a
  docker:
    - image: google/cloud-sdk

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: TAG_NAME=`git describe --tags`
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud --quiet config set project ${PROJECT_ID}
      - run: gcloud --quiet config set compute/zone ${COMPUTE_ZONE}
      - run: gcloud container builds submit --config=cloudbuild.yaml --substitutions REVISION_ID=$TAG_NAME .
  deploy-staging:
    <<: *defaults
    steps:
      - checkout
      - run: TAG_NAME=`git describe --tags`
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud --quiet config set project ${PROJECT_ID}
      - run: gcloud --quiet config set compute/zone ${COMPUTE_ZONE}
      - run: gcloud --quiet container clusters get-credentials --project ${STAGING_CLUSTER_PROJECT_ID} ${CLUSTER_NAME}
      - run: kubectl patch deployment web -p '{"spec":{"template":{"spec":{"containers":[{"name":"go-sample","image":"gcr.io/build-images/go_sample:'"$TAG_NAME"'"}]}}}}'
  deploy-production:
    <<: *defaults
    steps:
      - checkout
      - run: TAG_NAME=`git describe --tags`
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud --quiet config set project ${PROJECT_ID}
      - run: gcloud --quiet config set compute/zone ${COMPUTE_ZONE}
      - run: gcloud --quiet container clusters get-credentials --project ${PRODUCTION_CLUSTER_PROJECT_ID} ${CLUSTER_NAME}
      - run: kubectl patch deployment web -p '{"spec":{"template":{"spec":{"containers":[{"name":"go-sample","image":"gcr.io/build-images/go_sample:'"$TAG_NAME"'"}]}}}}'
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d\d\d\d\d\d\d\d\_\d*/
      - deploy-staging:
          requires:
            - build
      - hold:
          type: approval
          requires:
           - deploy-staging
      - deploy-production:
          requires:
            - hold
